<?php
/**
 * InvoicesApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  ServeXS\BolRetailer\v7
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * v7 - Retailer API
 *
 * The bol.com API for retailers.
 *
 * The version of the OpenAPI document: 7.x
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ServeXS\BolRetailer\v7\Test\Api;

use \ServeXS\BolRetailer\v7\Configuration;
use \ServeXS\BolRetailer\v7\ApiException;
use \ServeXS\BolRetailer\v7\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InvoicesApiTest Class Doc Comment
 *
 * @category Class
 * @package  ServeXS\BolRetailer\v7
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InvoicesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getInvoice
     *
     * Get an invoice by invoice id.
     *
     */
    public function testGetInvoice()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getInvoiceSpecification
     *
     * Get an invoice specification by invoice id.
     *
     */
    public function testGetInvoiceSpecification()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getInvoices
     *
     * Get all invoices.
     *
     */
    public function testGetInvoices()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
